---

- hosts: all
  become: true
  become_method: sudo
  become_user: root
  roles: 
    - common
    - useradd
    - userdel
    - python
    - php
    - mysql
    - nginx

  tasks:
  - name: reboot machine
    reboot:
      post_reboot_delay: 30
      msg: "Rebooting machine in 30 seconds"
